#!/usr/bin/python

import sys

print "static const char html[] = ";
for line in sys.stdin:
    foo = line.rstrip().replace("\\", "\\\\")
    print "\"" + foo.replace("\"", "\\\"") + "\\n\"";

    
print ";"
